### ISSUE TITLE
"Failed to get convolution algorithm" error when running with GPU

### ISSUE THREAD

**Issue by allo-** [allo-/simple_bodypix_python#1]
```
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v1_50/conv1/BatchNorm/batchnorm_1/add_1/conv}}]]
	 [[resnet_v1_50/displacement_bwd_2/BiasAdd/_15]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v1_50/conv1/BatchNorm/batchnorm_1/add_1/conv}}]]
0 successful operations.
0 derived errors ignored.

```

**Comment by fangfufu** [comment]
Please post a step-by-step walkthrough to recreate these errors.

**Comment by allo-** [comment]
This happens every time here.

- Create a virtualenv for the project, install the dependencies
- Get fake_webcam_background.py to run (test it using `CUDA_VISIBLE_DEVICES="" python fake_webcam_background.py`)
- Install tensorflow-gpu
- Run `python fake_webcam_background.py`

Currently I cannot be sure if it depends on my setup, but GPT-2 works with TF 2.1 and GPU on this machine.

**Comment by allo-** [comment]
Full backtrace:

```
Loading model...
done.
Traceback (most recent call last):
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node MobilenetV1/Conv2d_0/BatchNorm/batchnorm_1/add_1/conv}}]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node MobilenetV1/Conv2d_0/BatchNorm/batchnorm_1/add_1/conv}}]]
	 [[MobilenetV1/displacement_bwd_2/BiasAdd/_3]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fake_webcam_background.py", line 105, in <module>
    input_tensor: sample_image})
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
    run_metadata)
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node MobilenetV1/Conv2d_0/BatchNorm/batchnorm_1/add_1/conv (defined at tfjs-to-tf/tfjs_graph_converter/api.py:210) ]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node MobilenetV1/Conv2d_0/BatchNorm/batchnorm_1/add_1/conv (defined at tfjs-to-tf/tfjs_graph_converter/api.py:210) ]]
	 [[MobilenetV1/displacement_bwd_2/BiasAdd/_3]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node MobilenetV1/Conv2d_0/BatchNorm/batchnorm_1/add_1/conv:
 Const_55 (defined at tfjs-to-tf/tfjs_graph_converter/api.py:209)

Input Source operations connected to node MobilenetV1/Conv2d_0/BatchNorm/batchnorm_1/add_1/conv:
 Const_55 (defined at tfjs-to-tf/tfjs_graph_converter/api.py:209)

Original stack trace for 'MobilenetV1/Conv2d_0/BatchNorm/batchnorm_1/add_1/conv':
  File "fake_webcam_background.py", line 41, in <module>
    graph = tfjs.api.load_graph_model(modelPath)  # downloaded from the link above
  File "tfjs-to-tf/tfjs_graph_converter/api.py", line 261, in load_graph_model
    return _convert_graph_model_to_graph(model_json, model_path)
  File "tfjs-to-tf/tfjs_graph_converter/api.py", line 242, in _convert_graph_model_to_graph
    return _create_graph(graph_def, weight_dict, op_list)
  File "tfjs-to-tf/tfjs_graph_converter/api.py", line 210, in _create_graph
    tf.graph_util.import_graph_def(graph_def, weight_dict, name='')
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/importer.py", line 513, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/importer.py", line 243, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3459, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3459, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3347, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "simple_bodypix_python/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1756, in __init__
    self._traceback = tf_stack.extract_stack()

```
